site_name: BalancerX Docs
site_description: A lightweight, high-performance load balancer written in Go
site_author: Nishant
site_url: https://nishujangra.github.io/balancerx/

repo_name: nishujangra/balancerx
repo_url: https://github.com/nishujangra/balancerx
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    # OLED Black Dark Mode (default)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light mode (fallback, optional)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: gray
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

  icon:
    logo: material/notebook
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Load Balancing Strategies: user-guide/strategies.md
    - Protocols: user-guide/protocols.md
    - Logging: user-guide/logging.md
  - Performance:
    - Benchmarks: performance/benchmarks.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - admonition
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.blocks.definition
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
